
package com.company.main;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountryFinder", targetNamespace = "http://main.company.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountryFinder {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://main.company.com/CountryFinder/getCountryNameRequest", output = "http://main.company.com/CountryFinder/getCountryNameResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://main.company.com/CountryFinder/getCountryName/Fault/IOException")
    })
    public String getCountryName(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0)
        throws IOException_Exception
    ;

}
