
package com.company.main;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CountryFinderService", targetNamespace = "http://main.company.com/", wsdlLocation = "http://localhost:8080/SoapAndRestConnector/findCountry?wsdl")
public class CountryFinderService
    extends Service
{

    private final static URL COUNTRYFINDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTRYFINDERSERVICE_EXCEPTION;
    private final static QName COUNTRYFINDERSERVICE_QNAME = new QName("http://main.company.com/", "CountryFinderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SoapAndRestConnector/findCountry?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTRYFINDERSERVICE_WSDL_LOCATION = url;
        COUNTRYFINDERSERVICE_EXCEPTION = e;
    }

    public CountryFinderService() {
        super(__getWsdlLocation(), COUNTRYFINDERSERVICE_QNAME);
    }

    public CountryFinderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRYFINDERSERVICE_QNAME, features);
    }

    public CountryFinderService(URL wsdlLocation) {
        super(wsdlLocation, COUNTRYFINDERSERVICE_QNAME);
    }

    public CountryFinderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRYFINDERSERVICE_QNAME, features);
    }

    public CountryFinderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryFinderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CountryFinder
     */
    @WebEndpoint(name = "CountryFinderPort")
    public CountryFinder getCountryFinderPort() {
        return super.getPort(new QName("http://main.company.com/", "CountryFinderPort"), CountryFinder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryFinder
     */
    @WebEndpoint(name = "CountryFinderPort")
    public CountryFinder getCountryFinderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://main.company.com/", "CountryFinderPort"), CountryFinder.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRYFINDERSERVICE_EXCEPTION!= null) {
            throw COUNTRYFINDERSERVICE_EXCEPTION;
        }
        return COUNTRYFINDERSERVICE_WSDL_LOCATION;
    }

}
