
package com.company.fin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SendRequestsService", targetNamespace = "http://com.timex.bt.integration/", wsdlLocation = "http://124.123.41.79:7214/HttpGETSampleApp-GETBTIntegrationAPIProxy-context-root/SendRequestsPort?WSDL")
public class SendRequestsService
    extends Service
{

    private final static URL SENDREQUESTSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SENDREQUESTSSERVICE_EXCEPTION;
    private final static QName SENDREQUESTSSERVICE_QNAME = new QName("http://com.timex.bt.integration/", "SendRequestsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://124.123.41.79:7214/HttpGETSampleApp-GETBTIntegrationAPIProxy-context-root/SendRequestsPort?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDREQUESTSSERVICE_WSDL_LOCATION = url;
        SENDREQUESTSSERVICE_EXCEPTION = e;
    }

    public SendRequestsService() {
        super(__getWsdlLocation(), SENDREQUESTSSERVICE_QNAME);
    }

    public SendRequestsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDREQUESTSSERVICE_QNAME, features);
    }

    public SendRequestsService(URL wsdlLocation) {
        super(wsdlLocation, SENDREQUESTSSERVICE_QNAME);
    }

    public SendRequestsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDREQUESTSSERVICE_QNAME, features);
    }

    public SendRequestsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendRequestsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendRequests
     */
    @WebEndpoint(name = "SendRequestsPort")
    public SendRequests getSendRequestsPort() {
        return super.getPort(new QName("http://com.timex.bt.integration/", "SendRequestsPort"), SendRequests.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendRequests
     */
    @WebEndpoint(name = "SendRequestsPort")
    public SendRequests getSendRequestsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.timex.bt.integration/", "SendRequestsPort"), SendRequests.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDREQUESTSSERVICE_EXCEPTION!= null) {
            throw SENDREQUESTSSERVICE_EXCEPTION;
        }
        return SENDREQUESTSSERVICE_WSDL_LOCATION;
    }

}
