
package com.company.fin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendRequests", targetNamespace = "http://com.timex.bt.integration/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendRequests {


    /**
     * 
     * @param filepath
     * @param url
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://com.timex.bt.integration/")
    @RequestWrapper(localName = "getXmlData", targetNamespace = "http://com.timex.bt.integration/", className = "integration.bt.timex.com.GetXmlData")
    @ResponseWrapper(localName = "getXmlDataResponse", targetNamespace = "http://com.timex.bt.integration/", className = "integration.bt.timex.com.GetXmlDataResponse")
    public String getXmlData(
            @WebParam(name = "URL", targetNamespace = "http://com.timex.bt.integration/")
                    String url,
            @WebParam(name = "filepath", targetNamespace = "http://com.timex.bt.integration/")
                    String filepath)
        throws IOException_Exception
    ;

    /**
     * 
     * @param colMapFilepath
     * @param url
     * @param sql
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://com.timex.bt.integration/")
    @RequestWrapper(localName = "postData", targetNamespace = "http://com.timex.bt.integration/", className = "integration.bt.timex.com.PostData")
    @ResponseWrapper(localName = "postDataResponse", targetNamespace = "http://com.timex.bt.integration/", className = "integration.bt.timex.com.PostDataResponse")
    public String postData(
            @WebParam(name = "sql", targetNamespace = "http://com.timex.bt.integration/")
                    String sql,
            @WebParam(name = "url", targetNamespace = "http://com.timex.bt.integration/")
                    String url,
            @WebParam(name = "colMapFilepath", targetNamespace = "http://com.timex.bt.integration/")
                    String colMapFilepath)
        throws IOException_Exception
    ;

}
